#!/bin/bash

# Define the output file for the authors list
AUTHORS_FILE="AUTHORS"

# Initialize an empty authors file with the header
echo "# File @generated by authors.sh. DO NOT EDIT." > "$AUTHORS_FILE"
echo "# This file lists all contributors to the repository." >> "$AUTHORS_FILE"
echo "# See authors.sh to make modifications." >> "$AUTHORS_FILE"
echo "" >> "$AUTHORS_FILE"

# Use Git to get a list of contributors and append to the authors file
git log --format='%aN <%aE>' | sort -u >> "$AUTHORS_FILE"

echo "Authors file has been generated at $AUTHORS_FILE"
